services:
  App\Admin\CategoriesAdmin:
    arguments: [~,App\Entity\Category, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Категории, group: Ассортимент }
    public: true

  App\Admin\ProductsAdmin:
    arguments: [~,App\Entity\Product, ~ ]
    tags:
    - { name: sonata.admin, manager_type: orm, label: Товары, group: Ассортимент }
    public: true

  App\Admin\FeedbackRequestAdmin:
     arguments: [~,App\Entity\FeedbackRequest, ~ ]
     tags:
     - { name: sonata.admin, manager_type: orm, label: Обратная связь, group: Обращения }
     public: true

  App\Admin\ProductImagesAdmin:
    arguments: [~, App\Entity\ProductImage,~]
    tags:
      - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
    public: true

  App\Admin\CategoryImagesAdmin:
    arguments: [~,App\Entity\CategoryImage,~]
    tags:
      - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
    public: true